In [1]:
import os
import sys

sys.path.append(os.path.join(os.path.dirname(os.getcwd())))
sys.path.append(os.path.join(os.path.dirname(os.getcwd()), "src"))

import src.logging_cofig

In [2]:
import pandas as pd
from src.tokenizer_utils import load_tokenizer, tokenize

In [5]:
tokenizer = load_tokenizer("ai-sage/GigaChat3-10B-A1.8B-base")

2025-12-04 13:29:18 DEBUG    urllib3.connectionpool: Starting new HTTPS connection (1): huggingface.co:443
2025-12-04 13:29:18 DEBUG    urllib3.connectionpool: https://huggingface.co:443 "HEAD /ai-sage/GigaChat3-10B-A1.8B-base/resolve/main/tokenizer_config.json HTTP/1.1" 307 0
2025-12-04 13:29:19 DEBUG    urllib3.connectionpool: https://huggingface.co:443 "HEAD /api/resolve-cache/models/ai-sage/GigaChat3-10B-A1.8B-base/8092e7006e188b65fe10526a1b6472576645e5ed/tokenizer_config.json HTTP/1.1" 200 0
2025-12-04 13:29:19 DEBUG    urllib3.connectionpool: https://huggingface.co:443 "GET /api/models/ai-sage/GigaChat3-10B-A1.8B-base/tree/main/additional_chat_templates?recursive=False&expand=False HTTP/1.1" 404 64
2025-12-04 13:29:19 DEBUG    urllib3.connectionpool: https://huggingface.co:443 "GET /api/models/ai-sage/GigaChat3-10B-A1.8B-base/tree/main?recursive=True&expand=False HTTP/1.1" 200 5597
2025-12-04 13:29:20 DEBUG    urllib3.connectionpool: https://huggingface.co:443 "GET /api/models/ai-sage/GigaChat3-10B-A1.8B-base HTTP/1.1" 200 2015
2025-12-04 13:29:20 INFO     src.tokenizer_utils: Tokenizer adds prefix space

In [4]:
df = pd.read_csv("../hf_datasets/stimuli.csv")
df.head()

,sentence_id,sentence,congruent,structure,length,target,position,most_popular,percent,semantics_grammar,...,object_gender,object_ipm,gen_lemma,gen_length,gen_gender,gen_ipm,adj_lemma,adj_length,adj_gender,adj_ipm
0,0.0,Автобусы проходят массовую дезинфекцией,Автобусы проходят массовую дезинфекцию,Subject - Verb - Adj - Object,4.0,grammar,3.0,grammar,1.000000,NaN,...,femn,1.63,NaN,NaN,NaN,0.02,массовый,4.0,masc,50.834561
1,0.0,Автобусы проходят массовую дезинфекцию,Автобусы проходят массовую дезинфекцию,Subject - Verb - Adj - Object,4.0,normal,3.0,normal,0.833333,NaN,...,femn,1.63,NaN,NaN,NaN,0.02,массовый,4.0,masc,50.834561
2,0.0,Автобусы проходят массовую фортуной,Автобусы проходят массовую дезинфекцию,Subject - Verb - Adj - Object,4.0,semantics_grammar,3.0,semantics_grammar,1.000000,1.0,...,femn,1.63,NaN,NaN,NaN,0.02,массовый,4.0,masc,50.834561
3,0.0,Автобусы проходят массовую фортуну,Автобусы проходят массовую дезинфекцию,Subject - Verb - Adj - Object,4.0,semantics,3.0,semantics,1.000000,NaN,...,femn,1.63,NaN,NaN,NaN,0.02,массовый,4.0,masc,50.834561
4,2.0,Авторы получали подарками,Авторы получали подарки,Subject - Verb - Object,3.0,grammar,2.0,grammar,1.000000,NaN,...,masc,64.02,NaN,NaN,NaN,0.02,NaN,NaN,NaN,0.020000

In [14]:
# sentence = "Автобусы проходят массовую дезинфекцией"
# pos = 3
#
# word = sentence.split(" ")[pos]
# word_index = sentence.index(word)
# word_index
#
# # Надо рассмотреть два случая
# 1) len(splited) - 1 > pos
#
# 2) len(splited) - 1 == pos

27

In [26]:
# pad это [0,0] offets в конце

{'input_ids': tensor([[    1, 16553, 40079, 40500, 30876, 38701,   893, 59297,   560,  6637]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]), 'offset_mapping': tensor([[[ 0,  0],
         [ 0,  2],
         [ 2,  5],
         [ 5,  8],
         [ 8, 17],
         [17, 24],
         [24, 26],
         [26, 33],
         [33, 35],
         [35, 39]]])}

In [13]:
import numpy as np

np_hiddens = "/Users/ilyamikheev/Desktop/cuscience/SIGNAL-analysis/src/results/ai-sage_GigaChat3-10B-A1.8B-base/00000_ai-sage_GigaChat3-10B-A1.8B-base.npy"

hidden_states_sber = np.load(np_hiddens)

hidden_states_sber.shape

(12, 27, 1536)

In [16]:
hidden_states_sber[[7, 8, 9], :, :].mean(0)

array([[-5.30497218e-03, -8.83992482e-03,  3.45865893e-03, ...,
        -1.52079260e-03, -5.43212891e-03, -8.17871094e-03],
       [ 6.30335836e-03,  6.23843074e-03,  7.38133385e-04, ...,
        -1.27730295e-02,  5.65257808e-03, -1.69372763e-02],
       [ 1.87701564e-02,  9.73790884e-04,  1.30977975e-02, ...,
        -2.41141263e-02, -1.66391972e-02, -5.54515049e-04],
       ...,
       [-6.59994841e-01, -5.15554190e-01,  9.25656319e-01, ...,
        -3.72422367e-01,  3.46019119e-01, -9.01225865e-01],
       [-7.27447271e-01,  2.77094603e-01,  1.20827138e+00, ...,
        -1.24727100e-01,  3.53457361e-01, -1.08287251e+00],
       [-1.40886080e+00,  1.00682962e+00, -2.79180908e+00, ...,
        -3.19281995e-01, -5.12783885e-01, -4.37071413e-01]],
      shape=(27, 1536), dtype=float32)

In [11]:
from transformers import PreTrainedTokenizerFast
import numpy as np


def word_level_hidden_state(sentence_hidden_states: np.ndarray,
                            sentence: str,
                            word_position: int,
                            tokenizer: PreTrainedTokenizerFast,
                            strategy: str = "avg") -> np.ndarray:

    tokenizer_output = tokenize(
        tokenizer=tokenizer,
        sentences=[sentence],
    )

    words = sentence.split(" ")
    word = words[word_position]
    word_index = sentence.index(word)

    offset_mappings = tokenizer_output["offset_mapping"][0].tolist()
    offset_mapping_indices = []

    for i, offset_mappings in enumerate(offset_mappings):
        if offset_mappings[0] == offset_mappings[1] and offset_mappings[0] == 0:
            if i == 0:
                print("Skipp heading service token")
            else:
                print("Skipp trailing service token")
            continue
        if offset_mappings[0] >= word_index - 1:
            if word_position == len(words) - 1:
                offset_mapping_indices.append(i)
            else:
                next_word = words[word_position + 1]
                next_word_index = sentence.index(next_word)
                if offset_mappings[1] <= next_word_index:
                    offset_mapping_indices.append(i)
                else:
                    break

    if strategy == "avg":
        return sentence_hidden_states[offset_mapping_indices, :, :].mean(axis=0)
    else:
        raise ValueError("Strategy not implemented")

In [12]:
word_level_hidden_state(None, "Автобусы проходят массовую дезинфекцией", 3, tokenizer)

Skipp heading service token

[7, 8, 9]

In [10]:
sentence = "Автобусы проходят массовую дезинфекцией"
pos = 3

out = tokenize(
    tokenizer=tokenizer,
    sentences=[sentence, "Автобусы проходят массовую дезинфекцией" + "Автобусы проходят массовую дезинфекцией" + "Автобусы проходят массовую дезинфекцией"],
)

print(out)


word = sentence.split(" ")[pos]
word_index = sentence.index(word)

offset_mappings = out["offset_mapping"][0].tolist()

offset_mapping_indices = []

for i, offset_mappings in enumerate(offset_mappings):
    if offset_mappings[0] == offset_mappings[1] and offset_mappings[0] == 0:
        print("Skipp service token")
        continue
    if offset_mappings[0] >= word_index - 1:
        offset_mapping_indices.append(i)

offset_mapping_indices

{'input_ids': tensor([[    1, 16553, 40079, 40500, 30876, 38701,   893, 59297,   560,  6637,
             2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
             2,     2,     2,     2,     2,     2,     2,     2],
        [    1, 16553, 40079, 40500, 30876, 38701,   893, 59297,   560,  6637,
         16553, 40079, 40500, 30876, 38701,   893, 59297,   560,  6637, 16553,
         40079, 40500, 30876, 38701,   893, 59297,   560,  6637]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1]]), 'offset_mapping': tensor([[[  0,   0],
         [  0,   2],
         [  2,   5],
         [  5,   8],
         [  8,  17],
         [ 17,  24],
         [ 24,  26],
         [ 26,  33],
         [ 33,  35],
         [ 35,  39],
         [  0,   0],
         [  0,   0],
         [  0,   0],
         [  0,   0],
         [  0,   0],
         [  0,   0],
         [  0,   0],
         [  0,   0],
         [  0,   0],
         [  0,   0],
         [  0,   0],
         [  0,   0],
         [  0,   0],
         [  0,   0],
         [  0,   0],
         [  0,   0],
         [  0,   0],
         [  0,   0]],

        [[  0,   0],
         [  0,   2],
         [  2,   5],
         [  5,   8],
         [  8,  17],
         [ 17,  24],
         [ 24,  26],
         [ 26,  33],
         [ 33,  35],
         [ 35,  39],
         [ 39,  41],
         [ 41,  44],
         [ 44,  47],
         [ 47,  56],
         [ 56,  63],
         [ 63,  65],
         [ 65,  72],
         [ 72,  74],
         [ 74,  78],
         [ 78,  80],
         [ 80,  83],
         [ 83,  86],
         [ 86,  95],
         [ 95, 102],
         [102, 104],
         [104, 111],
         [111, 113],
         [113, 117]]])}
Skipp service token
Skipp service token
Skipp service token
Skipp service token
Skipp service token
Skipp service token
Skipp service token
Skipp service token
Skipp service token
Skipp service token
Skipp service token
Skipp service token
Skipp service token
Skipp service token
Skipp service token
Skipp service token
Skipp service token
Skipp service token
Skipp service token

[7, 8, 9]

In [5]:
df[(df["length"] == 4) & (df["position"] == 2)]

,sentence_id,sentence,congruent,structure,length,target,position,most_popular,percent,semantics_grammar,...,object_gender,object_ipm,gen_lemma,gen_length,gen_gender,gen_ipm,adj_lemma,adj_length,adj_gender,adj_ipm
12,4.0,Адвокат обжаловал воспоминание властей,Адвокат обжаловал решение властей,Subject - Verb - Object - Gen,4.0,semantics,2.0,semantics,1.0,NaN,...,neut,238.707454,власть,2.0,femn,358.675415,NaN,NaN,NaN,0.02
13,4.0,Адвокат обжаловал воспоминанием властей,Адвокат обжаловал решение властей,Subject - Verb - Object - Gen,4.0,semantics_grammar,2.0,semantics_grammar,1.0,1.0,...,neut,238.707454,власть,2.0,femn,358.675415,NaN,NaN,NaN,0.02
14,4.0,Адвокат обжаловал решение властей,Адвокат обжаловал решение властей,Subject - Verb - Object - Gen,4.0,normal,2.0,normal,1.0,NaN,...,neut,238.707454,власть,2.0,femn,358.675415,NaN,NaN,NaN,0.02
15,4.0,Адвокат обжаловал решением властей,Адвокат обжаловал решение властей,Subject - Verb - Object - Gen,4.0,grammar,2.0,grammar,1.0,NaN,...,neut,238.707454,власть,2.0,femn,358.675415,NaN,NaN,NaN,0.02
16,6.0,Администратор нажала кнопке сигнализации,Администратор нажала кнопку сигнализации,Subject - Verb - Object - Gen,4.0,grammar,2.0,grammar,1.0,NaN,...,femn,17.110000,сигнализация,6.0,femn,3.520000,NaN,NaN,NaN,0.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
575,312.0,Террористы занимают поколении аэропорта,Террористы занимают здание аэропорта,Subject - Verb - Object - Gen,4.0,semantics_grammar,2.0,semantics_grammar,1.0,1.0,...,neut,118.234752,аэропорт,5.0,masc,18.460000,NaN,NaN,NaN,0.02
592,334.0,Эксперты нашли конкурсами пота,Эксперты нашли следы пота,Subject - Verb - Object - Gen,4.0,semantics_grammar,2.0,semantics_grammar,1.0,1.0,...,masc,102.555755,пот,2.0,masc,33.170000,NaN,NaN,NaN,0.02
593,334.0,Эксперты нашли конкурсы пота,Эксперты нашли следы пота,Subject - Verb - Object - Gen,4.0,semantics,2.0,semantics,1.0,NaN,...,masc,102.555755,пот,2.0,masc,33.170000,NaN,NaN,NaN,0.02
594,334.0,Эксперты нашли следах пота,Эксперты нашли следы пота,Subject - Verb - Object - Gen,4.0,grammar,2.0,grammar,1.0,NaN,...,masc,102.555755,пот,2.0,masc,33.170000,NaN,NaN,NaN,0.02
595,334.0,Эксперты нашли следы пота,Эксперты нашли следы пота,Subject - Verb - Object - Gen,4.0,normal,2.0,normal,1.0,NaN,...,masc,102.555755,пот,2.0,masc,33.170000,NaN,NaN,NaN,0.02

In [4]:
df['sentence_list'].apply(lambda x: x.split())

0      Автобусы проходят массовую дезинфекцией
1       Автобусы проходят массовую дезинфекцию
2          Автобусы проходят массовую фортуной
3           Автобусы проходят массовую фортуну
4                    Авторы получали подарками
                        ...
595                  Эксперты нашли следы пота
596                     Эксперты сделали Париж
597                    Эксперты сделали Парижа
598                     Эксперты сделали вывод
599                    Эксперты сделали вывода
Name: sentence, Length: 600, dtype: object

In [6]:
from transformers import AutoTokenizer, AutoModelForCausalLM

In [9]:
model_name = "RefalMachine/ruadapt_qwen2.5_7B_ext_u48_instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

In [12]:
sent = "Автобусы проходят массовую дезинфекцией"

inputs = tokenizer(sent, return_tensors="pt")

In [14]:
outputs = model(**inputs)

In [15]:
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch
import math

# model_name = "gpt2"  # можно заменить на любую causal LM
# tokenizer = AutoTokenizer.from_pretrained(model_name)
# model = AutoModelForCausalLM.from_pretrained(model_name)
model.eval()

def compute_surprisal(text):
    # Токенизация
    inputs = tokenizer(text, return_tensors="pt")
    input_ids = inputs["input_ids"]

    # Прогон модели
    with torch.no_grad():
        outputs = model(input_ids, labels=input_ids)
        # logits: [batch, seq_len, vocab_size]
        logits = outputs.logits

    # Сдвигаем токены, чтобы каждый логит предсказывал следующий токен
    shifted_logits = logits[:, :-1, :]
    shifted_labels = input_ids[:, 1:]

    # Вычисляем распределение вероятностей
    log_probs = torch.log_softmax(shifted_logits, dim=-1)

    # Берём log p для правильных токенов
    token_log_probs = log_probs.gather(2, shifted_labels.unsqueeze(-1)).squeeze(-1)

    # surprisal = -log p
    surprisals = -token_log_probs

    # Декодируем токены для удобства
    tokens = tokenizer.convert_ids_to_tokens(shifted_labels[0])

    return list(zip(tokens, surprisals[0].tolist()))

# Пример
texts = ["Автобусы проходят массовую дезинфекцию", "Автобусы проходят массовую дезинфекцией"]

results = []

for text in texts:

    result = compute_surprisal(text)
    results.append(result)

    for tok, s in result:
        print(f"{tok:15} surprisal = {s:.4f}")

ÑĤ              surprisal = 3.1167
Ð¾Ð±            surprisal = 1.9628
ÑĥÑģÑĭ          surprisal = 0.9161
ĠÐ¿ÑĢÐ¾ÑħÐ¾Ð´ÑıÑĤ surprisal = 5.8601
ĠÐ¼Ð°ÑģÑģ       surprisal = 11.6478
Ð¾Ð²ÑĥÑİ        surprisal = 1.8316
ĠÐ´ÐµÐ·         surprisal = 3.4183
Ð¸Ð½ÑĦ          surprisal = 0.0076
ÐµÐº            surprisal = 0.0185
ÑĨÐ¸Ñİ          surprisal = 0.0005
ÑĤ              surprisal = 3.1167
Ð¾Ð±            surprisal = 1.9628
ÑĥÑģÑĭ          surprisal = 0.9161
ĠÐ¿ÑĢÐ¾ÑħÐ¾Ð´ÑıÑĤ surprisal = 5.8601
ĠÐ¼Ð°ÑģÑģ       surprisal = 11.6478
Ð¾Ð²ÑĥÑİ        surprisal = 1.8316
ĠÐ´ÐµÐ·         surprisal = 3.4183
Ð¸Ð½ÑĦ          surprisal = 0.0076
ÐµÐºÑĨÐ¸ÐµÐ¹    surprisal = 8.4325

In [2]:
import pandas as pd

df = pd.read_csv("../hf_datasets/stimuli.csv")

In [3]:
df.head()

,sentence_id,sentence,congruent,structure,length,target,position,most_popular,percent,semantics_grammar,...,object_gender,object_ipm,gen_lemma,gen_length,gen_gender,gen_ipm,adj_lemma,adj_length,adj_gender,adj_ipm
0,0.0,Автобусы проходят массовую дезинфекцией,Автобусы проходят массовую дезинфекцию,Subject - Verb - Adj - Object,4.0,grammar,3.0,grammar,1.000000,NaN,...,femn,1.63,NaN,NaN,NaN,0.02,массовый,4.0,masc,50.834561
1,0.0,Автобусы проходят массовую дезинфекцию,Автобусы проходят массовую дезинфекцию,Subject - Verb - Adj - Object,4.0,normal,3.0,normal,0.833333,NaN,...,femn,1.63,NaN,NaN,NaN,0.02,массовый,4.0,masc,50.834561
2,0.0,Автобусы проходят массовую фортуной,Автобусы проходят массовую дезинфекцию,Subject - Verb - Adj - Object,4.0,semantics_grammar,3.0,semantics_grammar,1.000000,1.0,...,femn,1.63,NaN,NaN,NaN,0.02,массовый,4.0,masc,50.834561
3,0.0,Автобусы проходят массовую фортуну,Автобусы проходят массовую дезинфекцию,Subject - Verb - Adj - Object,4.0,semantics,3.0,semantics,1.000000,NaN,...,femn,1.63,NaN,NaN,NaN,0.02,массовый,4.0,masc,50.834561
4,2.0,Авторы получали подарками,Авторы получали подарки,Subject - Verb - Object,3.0,grammar,2.0,grammar,1.000000,NaN,...,masc,64.02,NaN,NaN,NaN,0.02,NaN,NaN,NaN,0.020000

In [4]:
df.columns

Index(['sentence_id', 'sentence', 'congruent', 'structure', 'length', 'target',
       'position', 'most_popular', 'percent', 'semantics_grammar', 'semantics',
       'grammar', 'no', 'unknown', 'subject', 'verb', 'object', 'gen', 'adj',
       'subject_lemma', 'subject_length', 'subject_gender', 'subject_ipm',
       'verb_lemma', 'verb_length', 'verb_ipm', 'object_lemma',
       'object_length', 'object_gender', 'object_ipm', 'gen_lemma',
       'gen_length', 'gen_gender', 'gen_ipm', 'adj_lemma', 'adj_length',
       'adj_gender', 'adj_ipm'],
      dtype='object')

In [6]:
df['length'].unique()

array([4., 3.])

In [7]:
df['position'].unique()

array([3., 2.])

In [8]:
df[df['position'] < (df['length'] - 1)]

,sentence_id,sentence,congruent,structure,length,target,position,most_popular,percent,semantics_grammar,...,object_gender,object_ipm,gen_lemma,gen_length,gen_gender,gen_ipm,adj_lemma,adj_length,adj_gender,adj_ipm
12,4.0,Адвокат обжаловал воспоминание властей,Адвокат обжаловал решение властей,Subject - Verb - Object - Gen,4.0,semantics,2.0,semantics,1.0,NaN,...,neut,238.707454,власть,2.0,femn,358.675415,NaN,NaN,NaN,0.02
13,4.0,Адвокат обжаловал воспоминанием властей,Адвокат обжаловал решение властей,Subject - Verb - Object - Gen,4.0,semantics_grammar,2.0,semantics_grammar,1.0,1.0,...,neut,238.707454,власть,2.0,femn,358.675415,NaN,NaN,NaN,0.02
14,4.0,Адвокат обжаловал решение властей,Адвокат обжаловал решение властей,Subject - Verb - Object - Gen,4.0,normal,2.0,normal,1.0,NaN,...,neut,238.707454,власть,2.0,femn,358.675415,NaN,NaN,NaN,0.02
15,4.0,Адвокат обжаловал решением властей,Адвокат обжаловал решение властей,Subject - Verb - Object - Gen,4.0,grammar,2.0,grammar,1.0,NaN,...,neut,238.707454,власть,2.0,femn,358.675415,NaN,NaN,NaN,0.02
16,6.0,Администратор нажала кнопке сигнализации,Администратор нажала кнопку сигнализации,Subject - Verb - Object - Gen,4.0,grammar,2.0,grammar,1.0,NaN,...,femn,17.110000,сигнализация,6.0,femn,3.520000,NaN,NaN,NaN,0.02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
575,312.0,Террористы занимают поколении аэропорта,Террористы занимают здание аэропорта,Subject - Verb - Object - Gen,4.0,semantics_grammar,2.0,semantics_grammar,1.0,1.0,...,neut,118.234752,аэропорт,5.0,masc,18.460000,NaN,NaN,NaN,0.02
592,334.0,Эксперты нашли конкурсами пота,Эксперты нашли следы пота,Subject - Verb - Object - Gen,4.0,semantics_grammar,2.0,semantics_grammar,1.0,1.0,...,masc,102.555755,пот,2.0,masc,33.170000,NaN,NaN,NaN,0.02
593,334.0,Эксперты нашли конкурсы пота,Эксперты нашли следы пота,Subject - Verb - Object - Gen,4.0,semantics,2.0,semantics,1.0,NaN,...,masc,102.555755,пот,2.0,masc,33.170000,NaN,NaN,NaN,0.02
594,334.0,Эксперты нашли следах пота,Эксперты нашли следы пота,Subject - Verb - Object - Gen,4.0,grammar,2.0,grammar,1.0,NaN,...,masc,102.555755,пот,2.0,masc,33.170000,NaN,NaN,NaN,0.02
595,334.0,Эксперты нашли следы пота,Эксперты нашли следы пота,Subject - Verb - Object - Gen,4.0,normal,2.0,normal,1.0,NaN,...,masc,102.555755,пот,2.0,masc,33.170000,NaN,NaN,NaN,0.02